<?php

use Drupal\md_viewer\Constants\Constants;
/**
 * @file
 * A field formatter for the File field.
 *
 * This formatter renders the file as an embedded document,
 * using Microsoft's Documents viewer.
 */

/**
 * Implements hook_help().
 */
function md_viewer_help($route_name) {
  $helptext = '';
  if ($route_name == 'help.page.md_viewer') {
    $helptext = '<p>';
    $helptext .= t('This module provides a new format for the File field type. This format presents the file as a fully rendered object within a web page - i.e. it displays the contents of the file as appropriate to its filetype (Adobe Acrobat .pdf, Microsoft Word .doc/.docx, Microsoft Excel .xls/.xlsx, Microsoft Powerpoint .ppt/.pptx), using the Microsoft Document Viewer.');
    $helptext .= '</p>';
    $helptext .= '<p>';
    $helptext .= t("N.B.: Only files that are public may use this formatter - Microsoft Docs must be able to access the file in order to  render and display it. In other words, it won't work on a typical local development environment, or if your server is behind a firewall where microsoft is unable to access it.");
    $helptext .= '</p>';
    $helptext .= '<p>';
    $helptext .= t("To use this field format, add a File field to a new or existing content type (such as Basic Page) on the content type's Manage Fields form. The File field type provides only one widget type - File - so select that. On the content type's 'Manage Display' form, there will be a drop-down select list of available display formats for the File field. To display the file within the embedded Microsoft Docs viewer, choose the 'Embedded Microsoft Document Viewer Formatter' format.");
    $helptext .= '</p>';
    $helptext .= '<p>';
    $helptext .= t("The document viewer is styled using the mdoc-viewer-field.html.twig template.By default, the viewer's width is 100% and its height is 600px, with a frameborder zero. Provided field settings to change the width and height");
    $helptext .= '</p>';
  }
  return $helptext;
}

/**
 * Implements hook_theme().
 */
function md_viewer_theme() {
  return [
    'mdoc_viewer_field' => [
      'variables' => [
        'url' => NULL,
        'file_name' => NULL,
        'settings'  => [],
        'embed_link' => Constants::MD_VIEWER_MDOC_EMBEDD_LINK,
      ],
    ],
  ];
}
